#!/usr/bin/env node
/**
 * ai-atlas — SKILLS.md generator
 *
 * Scans skills folders for SKILL.md files, reads frontmatter (name, description,
 * metadata.domain, metadata.sdlc-stage) and regenerates SKILLS.md.
 *
 * Zero dependencies. Used by the release pipeline and by CI to enforce
 * index freshness (git diff after regeneration = stale index).
 *
 * Usage:  node scripts/gen-index.mjs [repo-root]
 */
import { readFileSync, writeFileSync, existsSync, readdirSync, mkdirSync } from "node:fs";
import { join, dirname, basename } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = process.argv[2] ?? join(HERE, "..");
const SKILLS_DIR = join(ROOT, "skills");

function findSkillDirs(dir) {
  if (!existsSync(dir)) return [];
  const found = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (existsSync(join(full, "SKILL.md"))) found.push(full);
      found.push(...findSkillDirs(full));
    }
  }
  return found;
}

function parseFrontmatter(md) {
  const m = md.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n/);
  if (!m) return {};
  const fields = {};
  for (const line of m[1].split(/\r?\n/)) {
    const idx = line.indexOf(":");
    if (idx <= 0) continue;
    const key = line.slice(0, idx).trim();
    let value = line.slice(idx + 1).trim().replace(/^["']|["']$/g, "");
    if (key === "metadata") {
      // multi-line metadata block — captured separately below; keep simple
      continue;
    }
    fields[key] = value;
  }
  // Parse nested metadata block (indented key: value under "metadata:")
  const metaMatch = m[1].match(/^metadata:\s*$/m);
  if (metaMatch) {
    const blockLines = m[1].split(/\r?\n/);
    const start = blockLines.findIndex((l) => l.trim() === "metadata:");
    fields.metadata = {};
    for (let i = start + 1; i < blockLines.length; i++) {
      const line = blockLines[i];
      if (!line || !line.startsWith("  ")) break;
      const idx = line.indexOf(":");
      if (idx < 0) continue;
      fields.metadata[line.slice(0, idx).trim()] = line.slice(idx + 1).trim().replace(/^["']|["']$/g, "");
    }
  }
  return fields;
}

const DOMAIN_LABELS = {
  "fnd-": "Foundation",
  "arch-": "Architect",
  "be-": "Developer Backend",
  "fe-": "Developer Frontend",
  "ui-": "UI Designer",
  "tst-": "Tester",
  "ops-": "DevOps",
};
const DOMAIN_ORDER = ["fnd-", "arch-", "be-", "fe-", "ui-", "tst-", "ops-"];
const prefixOf = (name) => DOMAIN_ORDER.find((p) => name.startsWith(p)) ?? "?";
const stageOf = (fm, name) =>
  (fm.metadata?.sdlcStage || fm.metadata?.["sdlc-stage"] || "").replace(/-/g, " ") || "—";

const skills = findSkillDirs(SKILLS_DIR)
  .map((dir) => ({ dir, fm: parseFrontmatter(readFileSync(join(dir, "SKILL.md"), "utf8")) }))
  .filter((s) => s.fm.name)
  .sort((a, b) => a.fm.name.localeCompare(b.fm.name));

const groups = new Map();
for (const p of DOMAIN_ORDER) groups.set(p, []);
for (const s of skills) {
  const prefix = prefixOf(s.fm.name);
  if (!groups.has(prefix)) groups.set(prefix, []);
  groups.get(prefix).push(s);
}

let out = `# ai-atlas — Skill Index

> Auto-generated by \`scripts/gen-index.mjs\` — do not edit by hand.
> Regenerate after adding or renaming a skill:

\`\`\`bash
node scripts/gen-index.mjs
\`\`\`

**${skills.length} skills published.**

`;
for (const [prefix, list] of groups) {
  if (list.length === 0) continue;
  out += `## ${DOMAIN_LABELS[prefix]}\n\n| Skill | Purpose | SDLC stage |\n|---|---|---|\n`;
  for (const s of list) out += `| \`${s.fm.name}\` | ${(s.fm.description ?? "").split(/\.\s/)[0].slice(0, 120)} | ${stageOf(s.fm, s.fm.name)} |\n`;
  out += "\n";
}

writeFileSync(join(ROOT, "SKILLS.md"), out, "utf8");
console.log(`generated SKILLS.md with ${skills.length} skills`);